<a href="https://colab.research.google.com/github/Kayla-afk/Tugas-Kuliah-D4-Sains-Data-Terapan/blob/main/DM_M4_3324600023_Kayla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd #untuk memanipulasi dataset
import numpy as np #untuk membantu dalam perhitungan numerik

In [3]:
#1. Menampilkan dataset
dataset = pd.read_csv('/content/titanic.csv')
print("Dataset Titanic: ")
dataset

Dataset Titanic:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
print(dataset.columns)

Index(['Age', 'Fare'], dtype='object')

In [4]:
#2. Menampilkan jumlah baris dan kolom
rows, cols = dataset.shape #shape digunakan untuk mengembalikan (rows, column)
print("Jumlah baris: ", rows)
print("Jumlah kolom: ", cols)

Jumlah baris:  891
Jumlah kolom:  12

In [6]:
#3. Megambil fitur (Age, Fare)
dataset = dataset[['Age', 'Fare']]
print("Fitur (Age dan Fare):")
dataset

Fitur (Age dan Fare):

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [17]:
#4. Mengambil kelas Survived
import pandas as pd

original_dataset = pd.read_csv('/content/titanic.csv')
kelas = original_dataset['Survived']

print("Class (Survived):")
kelas

Class (Survived):

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [19]:
#5. Mengisi missing value age berdasarkan mean masing-masing class
dataset['Survived'] = kelas

dataset['Age'] = dataset.groupby('Survived')['Age'].transform(
    lambda x: x.fillna(x.mean())
) #nilai age yang kosong diisi dengan mean dari class tersebut

print("Dataset setelah pengisian missing value Age:")
dataset[['Age', 'Fare', 'Survived']]

Dataset setelah pengisian missing value Age:

           Age     Fare  Survived
0    22.000000   7.2500         0
1    38.000000  71.2833         1
2    26.000000   7.9250         1
3    35.000000  53.1000         1
4    35.000000   8.0500         0
..         ...      ...       ...
886  27.000000  13.0000         0
887  19.000000  30.0000         1
888  30.626179  23.4500         0
889  26.000000  30.0000         1
890  32.000000   7.7500         0

[891 rows x 3 columns]

In [20]:
# Ambil data fitur setelah data preprocessing
data = dataset[['Age', 'Fare']]

print("Data setelah preprocessing:")
data

Data setelah preprocessing:

           Age     Fare
0    22.000000   7.2500
1    38.000000  71.2833
2    26.000000   7.9250
3    35.000000  53.1000
4    35.000000   8.0500
..         ...      ...
886  27.000000  13.0000
887  19.000000  30.0000
888  30.626179  23.4500
889  26.000000  30.0000
890  32.000000   7.7500

[891 rows x 2 columns]

In [21]:
#6. Normalisasi min-max
min_val = data.min()
max_val = data.max()

data_minmax = (data - min_val) / (max_val - min_val)

print("Hasil Normalisasi Min-Max (0-1):")
data_minmax

Hasil Normalisasi Min-Max (0-1):

          Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888  0.379570  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[891 rows x 2 columns]

In [22]:
#7. Normalisasi Z-Score
mean = data.mean()
std = data.std()

data_zscore = (data - mean) / std

print("Hasil Normalisasi Z-score:")
data_zscore

Hasil Normalisasi Z-score:

          Age      Fare
0   -0.595670 -0.502163
1    0.634089  0.786404
2   -0.288230 -0.488580
3    0.403509  0.420494
4    0.403509 -0.486064
..        ...       ...
886 -0.211370 -0.386454
887 -0.826250 -0.044356
888  0.067338 -0.176164
889 -0.288230 -0.044356
890  0.172929 -0.492101

[891 rows x 2 columns]

In [24]:
print("Mean setelah Z-score:")
print(data_zscore.mean())

print("\nStd setelah Z-score:")
print(data_zscore.std())

Mean setelah Z-score:
Age    -7.974666e-17
Fare   -7.974666e-18
dtype: float64

Std setelah Z-score:
Age     1.0
Fare    1.0
dtype: float64

In [23]:
#8. Normalisasi Sigmoidal
data_sigmoid = 1 / (1 + np.exp(-data))
print("Hasil Normalisasi Sigmoidal:")
data_sigmoid

Hasil Normalisasi Sigmoidal:

     Age      Fare
0    1.0  0.999290
1    1.0  1.000000
2    1.0  0.999639
3    1.0  1.000000
4    1.0  0.999681
..   ...       ...
886  1.0  0.999998
887  1.0  1.000000
888  1.0  1.000000
889  1.0  1.000000
890  1.0  0.999569

[891 rows x 2 columns]